{
  "status": "ERROR",
  "result": "Please log in and try again.",
  "errorCode": 10002,
  "errorInfo": {
    "description": "User attempted to access a method that required a user context without a user context.",
    "stack": "AssertionError: Query for request user context returned no UserContext\n    at userContextQuerySuccessCallback (/var/app/versions/v1/app/router/middleware/request/getUserContext.js:34:5)\n    at _fulfilled (/var/app/node_modules/q/q.js:787:54)\n    at self.promiseDispatch.done (/var/app/node_modules/q/q.js:816:30)\n    at Promise.promise.promiseDispatch (/var/app/node_modules/q/q.js:749:13)\n    at /var/app/node_modules/q/q.js:557:44\n    at flush (/var/app/node_modules/q/q.js:108:17)\n    at /var/app/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:177:31\n    at process._tickDomainCallback (node.js:459:13)\n    at process.<anonymous> (/var/app/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)",
    "data": null
  }
}
